#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2024 Robin Lindén <dev@robinlinden.eu>
#
# SPDX-License-Identifier: BSD-2-Clause

# Run all fuzz tests under a given pattern.
#
# Example usage:
# ./bzl/run_fuzz_tests starlark/... --config libfuzzer -c dbg -- --timeout_secs=3

set -euo pipefail

TARGETS=$(bazel query "filter(.*_fuzz_test_run$, $1)")
shift

for tgt in ${TARGETS}; do
  bazel run "$tgt" "$@"
done
