on:
  pull_request:
  workflow_dispatch:
name: ci

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

jobs:
  clang-format:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install --assume-yes --no-install-recommends clang-format-18
      - run: find . -name "*.h" -o -name "*.cc" | xargs clang-format-18 -style=file -i
      - run: git diff --exit-code

  buildifier:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: wget --output-document=buildifier https://github.com/bazelbuild/buildtools/releases/download/v8.2.1/buildifier-linux-amd64 && sudo chmod +x buildifier
      - run: ./buildifier --lint=warn --warnings=all -mode diff $(find . -type f -iname "*.build" -or -iname build -or -iname "*.bzl")

  prettier:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: npm install --global prettier@3.6.2
      - run: npx prettier --ignore-path .gitignore --write .
      - run: git diff --exit-code
