on:
  pull_request:
  workflow_dispatch:
name: ci

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

jobs:
  linux:
    name: linux-${{ matrix.name }}
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: gcc-14
            compiler: gcc
            version: 14

          - name: clang-18
            compiler: clang
            version: 18

    steps:
      - name: Setup gcc
        if: startsWith(matrix.compiler, 'gcc')
        run: |
          echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
      - name: Setup clang
        if: startsWith(matrix.compiler, 'clang')
        run: |
          echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
      - uses: actions/checkout@v5
      - name: Install
        if: ${{ !matrix.skip-compiler-install }}
        run: |
          sudo apt-get update
          sudo apt-get install --assume-yes --no-install-recommends ${{ matrix.compiler }}-${{ matrix.version }}
      - run: bazel test ...

  clang-format:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - run: sudo apt-get update && sudo apt-get install --assume-yes --no-install-recommends clang-format-18
      - run: find . -name "*.h" -o -name "*.cc" | xargs clang-format-18 -style=file -i
      - run: git diff --exit-code

  buildifier:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - run: wget --output-document=buildifier https://github.com/bazelbuild/buildtools/releases/download/v8.2.1/buildifier-linux-amd64 && sudo chmod +x buildifier
      - run: ./buildifier --lint=warn --warnings=all -mode diff $(find . -type f -iname "*.build" -or -iname build -or -iname "*.bzl")

  prettier:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - run: npm install --global prettier@3.6.2
      - run: npx prettier --ignore-path .gitignore --write .
      - run: git diff --exit-code
